version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: test-db
    restart: always
    environment:
      - POSTGRES_DB=jesttest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes:
      - postgres:/var/lib/postgresql/data
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/src
    image: node:16.18.1-alpine
    container_name: test-api
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_PASSWORD=postgres
      - DB_USERNAME=postgres
      - DB_NAME=jesttest
      - DB_HOST=test-db
      - DB_PORT=5432
    command: npm run dev
    ports:
      - '4000:4000'
    networks:
      - app-network
    depends_on:
      - postgres
      
networks:
  app-network:
    driver: bridge

volumes:
  postgres:
    driver: local
