version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/src
    image: node:16.18.1-alpine
    container_name: todo-api
    restart: unless-stopped
    env_file: .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@todo-db:5432/jesttest
      - JWT_SECRET_KEY=mem
    command: npm run dev
    ports:
      - '4000:4000'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
