version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: todo-db
    restart: always
    environment:
      - POSTGRES_DB=jesttest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - app-network
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
    driver: local
