version: '3.8'

services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=jesttest
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    networks:
      - default
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
    driver: local
